language: java
node_js: "8.10.0"
sudo: required
before_install:
- openssl aes-256-cbc -k "$GPG_PASSPHRASE" -in codesigning.asc.enc -out codesigning.asc -d
- gpg --fast-import codesigning.asc
# Check Ant Media Server from git if tagged build, in order to fix dependency issue
- (if [ ! -z "$TRAVIS_TAG" ];
    then
       echo "This build is tag with $TRAVIS_TAG. Check Ant Media Server $TRAVIS_TAG";
       git clone --depth=1 -b $TRAVIS_TAG https://github.com/ant-media/Ant-Media-Server.git; 
       cd Ant-Media-Server;
       mvn clean install -DskipTests -Dgpg.skip=true --quiet;
       cd ..;
    else 
       echo "This is not a tagged build. Checkout Ant Media Server from maven repo";
  fi)
- npm install -g @angular/cli@6.0.5
- sudo git clone --depth=1 https://github.com/ant-media/ManagementConsole_AngularApp.git
- sudo chown -R `whoami` ./ManagementConsole_AngularApp
- cd ManagementConsole_AngularApp
- npm install
- ng build --prod
- cd ..
- sudo cp -a ./ManagementConsole_AngularApp/dist/. ./src/main/webapp/

install:
- mvn install -DskipTests=true -Dmaven.javadoc.skip=true -Dgpg.skip=true -B -V --quiet
script: 
cache:
  directories:
  - "$HOME/.m2/repository"
deploy:
- provider: script
  script: mvn deploy -DskipTests --quiet --settings mvn-settings.xml
  skip_cleanup: true
  on:
    tags: false
    all_branches: true
    condition: $(mvn -q -Dexec.executable="echo" -Dexec.args='${project.version}'
      --non-recursive exec:exec)  = *"SNAPSHOT"*
- provider: script
  script: mvn deploy -DskipTests --quiet --settings mvn-settings.xml
  skip_cleanup: true
  on:
    tags: true
    branch: master
